CREATE TABLE LAWYER_DETAILS(
     	   AEN VARCHAR(30) PRIMARY KEY,
	   LAWYER_NAME VARCHAR(20)  NOT NULL,
	   LAWYER_TYPE VARCHAR(30) ,
	   GENDER VARCHAR(6) NOT NULL,
	   CONTACT_NO BIGINT NOT NULL,
	   YEARS_OF_EXPERIENCE INT NOT NULL,
	   FEES INT ,
     	   TOTAL_CASES INT NOT NULL,
	   WIN_PERCENTAGE DOUBLE PRECISION NOT NULL,
	   ADDRESS VARCHAR(50),
	   STATE VARCHAR(20),
    	   CITY VARCHAR(20),
	   ASSOCIATION_FLAG VARCHAR(20)
);

CREATE TABLE CASE_DETAILS (
	   CASE_NO VARCHAR(50) PRIMARY KEY,
	   DATE_OF_APPLICATION DATE NOT NULL,
	   CATEGORY VARCHAR(50) NOT NULL,
	   CASE_STATUS VARCHAR(50) NOT NULL
);

CREATE TABLE PENAL_CODE(
	   SECTION_CODE VARCHAR(10),
	   CODE_TYPE VARCHAR(10),
	   DESCRIPTION TEXT NOT NULL,
	   PRIMARY KEY(SECTION_CODE,CODE_TYPE)
);

CREATE TABLE BASED_ON(
	   CASE_NO VARCHAR(50) REFERENCES CASE_DETAILS(CASE_NO) ON UPDATE CASCADE ON DELETE CASCADE,
	   CODE_TYPE VARCHAR(10),
	   SECTION_CODE VARCHAR(10),
	   PRIMARY KEY(CASE_NO,CODE_TYPE,SECTION_CODE),
    	   FOREIGN KEY(CODE_TYPE,SECTION_CODE) REFERENCES PENAL_CODE ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ADVOCATED_BY(
     	   CASE_NO VARCHAR(50) REFERENCES CASE_DETAILS ON UPDATE CASCADE ON DELETE CASCADE,
     	   AEN VARCHAR(30) REFERENCES LAWYER_DETAILS ON UPDATE CASCADE ON DELETE CASCADE,
     	   PRIMARY KEY(CASE_NO,AEN)
);

CREATE TABLE FIRM_DETAILS(
	   FIRM_ID VARCHAR(20) PRIMARY KEY,
	   FIRM_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE LAWYER_UNDER_FIRM(
     	   AEN VARCHAR(30) REFERENCES LAWYER_DETAILS ON UPDATE CASCADE ON DELETE CASCADE,
    	   FIRM_ID VARCHAR(20) REFERENCES FIRM_DETAILS ON UPDATE CASCADE ON DELETE CASCADE,
	   PRIMARY KEY(AEN,FIRM_ID)
);

CREATE TABLE CRIMINAL_CASES(
	   FIR_ID VARCHAR(20) PRIMARY KEY,
	   FIR_DESC TEXT NOT NULL,
	   POLICE_STATION VARCHAR(30),
     	   CASE_NO VARCHAR(50) REFERENCES CASE_DETAILS ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE LITIGANTS(
	   AADHAR_NO BIGINT PRIMARY KEY,
	   LITIGANT_NAME VARCHAR(30) NOT NULL,
	   GENDER VARCHAR(6) NOT NULL,
	   Dob DATE NOT NULL,
	   AGE INT NOT NULL
);

CREATE TABLE PLAINTIFF(        
     	   CASE_NO VARCHAR(50) REFERENCES CASE_DETAILS ON UPDATE CASCADE ON DELETE CASCADE,
     	   AADHAR_NO BIGINT REFERENCES LITIGANTS ON UPDATE CASCADE ON DELETE CASCADE,
	   PRIMARY KEY(CASE_NO,AADHAR_NO)
);

CREATE TABLE DEFENDENT(
     	   CASE_NO VARCHAR(50) REFERENCES CASE_DETAILS ON UPDATE CASCADE ON DELETE CASCADE,
     	   AADHAR_NO BIGINT REFERENCES LITIGANTS ON UPDATE CASCADE ON DELETE CASCADE,
     	   PRIMARY KEY(CASE_NO,AADHAR_NO)
);

CREATE TABLE JUDGE_DETAILS(
     	   JUDGE_ID VARCHAR(30) PRIMARY KEY,
	   JUDGE_NAME VARCHAR(50) NOT NULL,
	   GENDER VARCHAR(6) NOT NULL,
	   POSITION VARCHAR(30) NOT NULL,
	   APPOINTMENT_DATE DATE NOT NULL,
	   QUALIFICATION VARCHAR(30) NOT NULL,
	   RETIREMENT_DATE DATE NOT NULL,
	   YEARS_OF_EXPERIENCE INT NOT NULL,
	   FORMER_CURRENT VARCHAR(7) NOT NULL,
	   COURT_NAME VARCHAR(30) NOT NULL
);

CREATE TABLE COURTS(
           COURT_NAME VARCHAR(30) PRIMARY KEY,
	   TYPE VARCHAR(30) NOT NULL,
	   LOCATION VARCHAR(80) NOT NULL
);

CREATE TABLE COURT_ROOMS(
           COURT_NAME VARCHAR(30) REFERENCES COURTS ON UPDATE CASCADE ON DELETE CASCADE,
	   ROOM_NO VARCHAR(10) ,
	   TEL_EXTN_NO INT,
	   PRIMARY KEY(COURT_NAME,ROOM_NO)
);

CREATE TABLE REGISTRARS(
	   REGISTRAR_ID VARCHAR(20) PRIMARY KEY,
	   NAME VARCHAR(30) NOT NULL,
	   DESIGNATION VARCHAR(20) NOT NULL,
           COURT_NAME VARCHAR(30) REFERENCES COURTS ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE COMMITEE(
           JUDGE_ID VARCHAR(30) REFERENCES JUDGE_DETAILS ON UPDATE CASCADE ON DELETE CASCADE,
	   COMMITEE_TYPE VARCHAR(30) ,
	   PRIMARY KEY(JUDGE_ID,COMMITEE_TYPE)
);

CREATE TABLE WITNESSES(          
           AADHAR_NO BIGINT PRIMARY KEY,
	   WITNESS_NAME VARCHAR(50),
	   CONTACT_NO BIGINT 	
);

CREATE TABLE ADJUDICATED_BY(
           CASE_NO VARCHAR(50) REFERENCES CASE_DETAILS ON UPDATE CASCADE ON DELETE CASCADE,
           JUDGE_ID VARCHAR(30) REFERENCES JUDGE_DETAILS ON UPDATE CASCADE ON DELETE CASCADE,
 	   PRIMARY KEY(CASE_NO,JUDGE_ID)
);

CREATE TABLE SCHEDULE(
           CASE_NO VARCHAR(50) REFERENCES CASE_DETAILS ON UPDATE CASCADE ON DELETE CASCADE, 
	   "TIME" TIME,
	   "DATE" DATE,
	   NO_OF_HEARING INT NOT NULL,
	   VERDICT TEXT,
	   COURT_NAME VARCHAR(30),
	   ROOM_NO VARCHAR(10),
           FOREIGN KEY(COURT_NAME,ROOM_NO) REFERENCES COURT_ROOMS ON UPDATE CASCADE ON DELETE CASCADE,
           PRIMARY KEY(CASE_NO,"TIME","DATE",COURT_NAME,ROOM_NO)
);

CREATE TABLE APPEARED_IN(             
	   AADHAR_NO BIGINT REFERENCES  WITNESSES ,
	   CASE_NO VARCHAR(50) REFERENCES CASE_DETAILS,
           WITNESS_TYPE VARCHAR(50),
	   CALLED_BY VARCHAR(50),
	   TESTIMONY_DATE DATE ,
	   PRIMARY KEY(AADHAR_NO , CASE_NO)
);
